changelog:
  exclude:
    authors:
      - dependabot
      - dependabot[bot]
      - github-actions
      - github-actions[bot]
    labels:
      - ignore-for-release
      - release
  categories:
    - title: Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - fix
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
