package com.prateek.taro.achievements

import androidx.annotation.StringRes
import com.prateek.taro.R

enum class SkillGroup(@StringRes val label: Int, val category: BadgeCategory) {
    PULL(R.string.skill_group_pull, BadgeCategory.SKILLS),
    PUSH(R.string.skill_group_push, BadgeCategory.SKILLS),
    CORE(R.string.skill_group_core, BadgeCategory.SKILLS),
    LEGS(R.string.skill_group_legs, BadgeCategory.SKILLS),
    LEVERS(R.string.skill_group_levers, BadgeCategory.SKILLS),
    BALANCE(R.string.skill_group_balance, BadgeCategory.SKILLS),
    BENCH(R.string.skill_group_bench, BadgeCategory.STRENGTH),
    SQUAT(R.string.skill_group_squat, BadgeCategory.STRENGTH),
    DEADLIFT(R.string.skill_group_deadlift, BadgeCategory.STRENGTH),
    OVERHEAD(R.string.skill_group_overhead, BadgeCategory.STRENGTH),
    WEIGHTED(R.string.skill_group_weighted, BadgeCategory.STRENGTH),
    CLUBS(R.string.skill_group_clubs, BadgeCategory.STRENGTH),
}

object Skills {
    private fun skill(id: String, group: SkillGroup, title: Int, description: Int, icon: Int) =
        BadgeDef(id, group.category, title, description, icon, 1.0, BadgeUnit.FLAG, { Rules.flag(it.claimed[id]) }, claimable = true, group = group)

    val badges: List<BadgeDef> = listOf(
        skill("dead_hang", SkillGroup.PULL, R.string.badge_dead_hang, R.string.badge_desc_dead_hang, R.drawable.ic_skill_hang),
        skill("first_pullup", SkillGroup.PULL, R.string.badge_first_pullup, R.string.badge_desc_first_pullup, R.drawable.ic_skill_pullup),
        skill("pullups_5", SkillGroup.PULL, R.string.badge_pullups_5, R.string.badge_desc_pullups_5, R.drawable.ic_skill_pullup),
        skill("ten_pullups", SkillGroup.PULL, R.string.badge_ten_pullups, R.string.badge_desc_ten_pullups, R.drawable.ic_skill_pullup),
        skill("pullups_20", SkillGroup.PULL, R.string.badge_pullups_20, R.string.badge_desc_pullups_20, R.drawable.ic_skill_pullup),
        skill("archer_pullup", SkillGroup.PULL, R.string.badge_archer_pullup, R.string.badge_desc_archer_pullup, R.drawable.ic_skill_pullup),
        skill("typewriter", SkillGroup.PULL, R.string.badge_typewriter, R.string.badge_desc_typewriter, R.drawable.ic_skill_pullup),
        skill("muscle_up", SkillGroup.PULL, R.string.badge_muscle_up, R.string.badge_desc_muscle_up, R.drawable.ic_skill_muscleup),
        skill("ring_muscle_up", SkillGroup.PULL, R.string.badge_ring_muscle_up, R.string.badge_desc_ring_muscle_up, R.drawable.ic_skill_muscleup),
        skill("one_arm_pullup", SkillGroup.PULL, R.string.badge_one_arm_pullup, R.string.badge_desc_one_arm_pullup, R.drawable.ic_skill_onearm),
        skill("pushups_20", SkillGroup.PUSH, R.string.badge_pushups_20, R.string.badge_desc_pushups_20, R.drawable.ic_skill_pushup),
        skill("pushups_50", SkillGroup.PUSH, R.string.badge_pushups_50, R.string.badge_desc_pushups_50, R.drawable.ic_skill_pushup),
        skill("diamond_pushups", SkillGroup.PUSH, R.string.badge_diamond_pushups, R.string.badge_desc_diamond_pushups, R.drawable.ic_skill_pushup),
        skill("archer_pushup", SkillGroup.PUSH, R.string.badge_archer_pushup, R.string.badge_desc_archer_pushup, R.drawable.ic_skill_pushup),
        skill("pseudo_planche_pushup", SkillGroup.PUSH, R.string.badge_pseudo_planche_pushup, R.string.badge_desc_pseudo_planche_pushup, R.drawable.ic_skill_pushup),
        skill("one_arm_pushup", SkillGroup.PUSH, R.string.badge_one_arm_pushup, R.string.badge_desc_one_arm_pushup, R.drawable.ic_skill_pushup),
        skill("dips_10", SkillGroup.PUSH, R.string.badge_dips_10, R.string.badge_desc_dips_10, R.drawable.ic_skill_dip),
        skill("dips_20", SkillGroup.PUSH, R.string.badge_dips_20, R.string.badge_desc_dips_20, R.drawable.ic_skill_dip),
        skill("ring_dips", SkillGroup.PUSH, R.string.badge_ring_dips, R.string.badge_desc_ring_dips, R.drawable.ic_skill_dip),
        skill("hspu", SkillGroup.PUSH, R.string.badge_hspu, R.string.badge_desc_hspu, R.drawable.ic_skill_hspu),
        skill("free_hspu", SkillGroup.PUSH, R.string.badge_free_hspu, R.string.badge_desc_free_hspu, R.drawable.ic_skill_hspu),
        skill("hollow_hold", SkillGroup.CORE, R.string.badge_hollow_hold, R.string.badge_desc_hollow_hold, R.drawable.ic_skill_hollow),
        skill("l_sit", SkillGroup.CORE, R.string.badge_l_sit, R.string.badge_desc_l_sit, R.drawable.ic_skill_lsit),
        skill("v_sit", SkillGroup.CORE, R.string.badge_v_sit, R.string.badge_desc_v_sit, R.drawable.ic_skill_lsit),
        skill("toes_to_bar", SkillGroup.CORE, R.string.badge_toes_to_bar, R.string.badge_desc_toes_to_bar, R.drawable.ic_skill_toes),
        skill("dragon_flag", SkillGroup.CORE, R.string.badge_dragon_flag, R.string.badge_desc_dragon_flag, R.drawable.ic_skill_dragonflag),
        skill("manna", SkillGroup.CORE, R.string.badge_manna, R.string.badge_desc_manna, R.drawable.ic_skill_lsit),
        skill("squats_100", SkillGroup.LEGS, R.string.badge_squats_100, R.string.badge_desc_squats_100, R.drawable.ic_skill_squat),
        skill("pistol", SkillGroup.LEGS, R.string.badge_pistol, R.string.badge_desc_pistol, R.drawable.ic_skill_pistol),
        skill("shrimp_squat", SkillGroup.LEGS, R.string.badge_shrimp_squat, R.string.badge_desc_shrimp_squat, R.drawable.ic_skill_pistol),
        skill("nordic_curl", SkillGroup.LEGS, R.string.badge_nordic_curl, R.string.badge_desc_nordic_curl, R.drawable.ic_skill_nordic),
        skill("skin_the_cat", SkillGroup.LEVERS, R.string.badge_skin_the_cat, R.string.badge_desc_skin_the_cat, R.drawable.ic_skill_backlever),
        skill("tuck_front_lever", SkillGroup.LEVERS, R.string.badge_tuck_front_lever, R.string.badge_desc_tuck_front_lever, R.drawable.ic_skill_frontlever),
        skill("adv_tuck_front_lever", SkillGroup.LEVERS, R.string.badge_adv_tuck_front_lever, R.string.badge_desc_adv_tuck_front_lever, R.drawable.ic_skill_frontlever),
        skill("straddle_front_lever", SkillGroup.LEVERS, R.string.badge_straddle_front_lever, R.string.badge_desc_straddle_front_lever, R.drawable.ic_skill_frontlever),
        skill("front_lever", SkillGroup.LEVERS, R.string.badge_front_lever, R.string.badge_desc_front_lever, R.drawable.ic_skill_frontlever),
        skill("tuck_back_lever", SkillGroup.LEVERS, R.string.badge_tuck_back_lever, R.string.badge_desc_tuck_back_lever, R.drawable.ic_skill_backlever),
        skill("back_lever", SkillGroup.LEVERS, R.string.badge_back_lever, R.string.badge_desc_back_lever, R.drawable.ic_skill_backlever),
        skill("human_flag", SkillGroup.LEVERS, R.string.badge_human_flag, R.string.badge_desc_human_flag, R.drawable.ic_skill_flag),
        skill("crow", SkillGroup.BALANCE, R.string.badge_crow, R.string.badge_desc_crow, R.drawable.ic_skill_crow),
        skill("wall_handstand", SkillGroup.BALANCE, R.string.badge_wall_handstand, R.string.badge_desc_wall_handstand, R.drawable.ic_skill_handstand),
        skill("handstand_10", SkillGroup.BALANCE, R.string.badge_handstand_10, R.string.badge_desc_handstand_10, R.drawable.ic_skill_handstand),
        skill("handstand", SkillGroup.BALANCE, R.string.badge_handstand, R.string.badge_desc_handstand, R.drawable.ic_skill_handstand),
        skill("handstand_60", SkillGroup.BALANCE, R.string.badge_handstand_60, R.string.badge_desc_handstand_60, R.drawable.ic_skill_handstand),
        skill("press_handstand", SkillGroup.BALANCE, R.string.badge_press_handstand, R.string.badge_desc_press_handstand, R.drawable.ic_skill_handstand),
        skill("tuck_planche", SkillGroup.BALANCE, R.string.badge_tuck_planche, R.string.badge_desc_tuck_planche, R.drawable.ic_skill_planche),
        skill("planche", SkillGroup.BALANCE, R.string.badge_planche, R.string.badge_desc_planche, R.drawable.ic_skill_planche),
        skill("full_planche", SkillGroup.BALANCE, R.string.badge_full_planche, R.string.badge_desc_full_planche, R.drawable.ic_skill_planche),
        skill("bench_40", SkillGroup.BENCH, R.string.badge_bench_40, R.string.badge_desc_bench_40, R.drawable.ic_skill_bench),
        skill("bench_plate", SkillGroup.BENCH, R.string.badge_bench_plate, R.string.badge_desc_bench_plate, R.drawable.ic_skill_bench),
        skill("bench_bw", SkillGroup.BENCH, R.string.badge_bench_bw, R.string.badge_desc_bench_bw, R.drawable.ic_skill_bench),
        skill("bench_100", SkillGroup.BENCH, R.string.badge_bench_100, R.string.badge_desc_bench_100, R.drawable.ic_skill_bench),
        skill("bench_1_5", SkillGroup.BENCH, R.string.badge_bench_1_5, R.string.badge_desc_bench_1_5, R.drawable.ic_skill_bench),
        skill("squat_60", SkillGroup.SQUAT, R.string.badge_squat_60, R.string.badge_desc_squat_60, R.drawable.ic_skill_liftsquat),
        skill("squat_two_plate", SkillGroup.SQUAT, R.string.badge_squat_two_plate, R.string.badge_desc_squat_two_plate, R.drawable.ic_skill_liftsquat),
        skill("squat_bw", SkillGroup.SQUAT, R.string.badge_squat_bw, R.string.badge_desc_squat_bw, R.drawable.ic_skill_liftsquat),
        skill("squat_140", SkillGroup.SQUAT, R.string.badge_squat_140, R.string.badge_desc_squat_140, R.drawable.ic_skill_liftsquat),
        skill("squat_2", SkillGroup.SQUAT, R.string.badge_squat_2, R.string.badge_desc_squat_2, R.drawable.ic_skill_liftsquat),
        skill("deadlift_100", SkillGroup.DEADLIFT, R.string.badge_deadlift_100, R.string.badge_desc_deadlift_100, R.drawable.ic_skill_deadlift),
        skill("deadlift_three_plate", SkillGroup.DEADLIFT, R.string.badge_deadlift_three_plate, R.string.badge_desc_deadlift_three_plate, R.drawable.ic_skill_deadlift),
        skill("deadlift_bw", SkillGroup.DEADLIFT, R.string.badge_deadlift_bw, R.string.badge_desc_deadlift_bw, R.drawable.ic_skill_deadlift),
        skill("deadlift_180", SkillGroup.DEADLIFT, R.string.badge_deadlift_180, R.string.badge_desc_deadlift_180, R.drawable.ic_skill_deadlift),
        skill("deadlift_2_5", SkillGroup.DEADLIFT, R.string.badge_deadlift_2_5, R.string.badge_desc_deadlift_2_5, R.drawable.ic_skill_deadlift),
        skill("press_40", SkillGroup.OVERHEAD, R.string.badge_press_40, R.string.badge_desc_press_40, R.drawable.ic_skill_press),
        skill("press_60", SkillGroup.OVERHEAD, R.string.badge_press_60, R.string.badge_desc_press_60, R.drawable.ic_skill_press),
        skill("press_bw", SkillGroup.OVERHEAD, R.string.badge_press_bw, R.string.badge_desc_press_bw, R.drawable.ic_skill_press),
        skill("weighted_pullup_10", SkillGroup.WEIGHTED, R.string.badge_weighted_pullup_10, R.string.badge_desc_weighted_pullup_10, R.drawable.ic_skill_weighted),
        skill("weighted_pullup", SkillGroup.WEIGHTED, R.string.badge_weighted_pullup, R.string.badge_desc_weighted_pullup, R.drawable.ic_skill_weighted),
        skill("weighted_pullup_40", SkillGroup.WEIGHTED, R.string.badge_weighted_pullup_40, R.string.badge_desc_weighted_pullup_40, R.drawable.ic_skill_weighted),
        skill("weighted_dip_20", SkillGroup.WEIGHTED, R.string.badge_weighted_dip_20, R.string.badge_desc_weighted_dip_20, R.drawable.ic_skill_dip),
        skill("weighted_dip_50", SkillGroup.WEIGHTED, R.string.badge_weighted_dip_50, R.string.badge_desc_weighted_dip_50, R.drawable.ic_skill_dip),
        skill("thousand_club", SkillGroup.CLUBS, R.string.badge_thousand_club, R.string.badge_desc_thousand_club, R.drawable.ic_skill_plates),
        skill("twelve_hundred_club", SkillGroup.CLUBS, R.string.badge_twelve_hundred_club, R.string.badge_desc_twelve_hundred_club, R.drawable.ic_skill_plates),
    )
}
