plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'com.nvllz.stepsy'
    compileSdk 35
    defaultConfig {
        applicationId "com.nvllz.stepsy"
        minSdkVersion 26
        targetSdkVersion 35
        versionCode 20
        versionName "1.6.2"
        proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
    flavorDimensions += "distribution"

    productFlavors {
        create("full") {
            dimension = "distribution"
            buildConfigField "boolean", "HAS_PROPRIETARY_LIBRARIES", "true"
        }
        create("foss") {
            dimension = "distribution"
            buildConfigField "boolean", "HAS_PROPRIETARY_LIBRARIES", "false"
        }
    }
    signingConfigs {
        release {
            storeFile file("keystore.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
        }
    }
    buildTypes {
        debug {
            manifestPlaceholders = [icon: "@drawable/ic_launcher_debug"]
            applicationIdSuffix ".debug"
            versionNameSuffix '-debug'
            minifyEnabled false
        }
        release {
            manifestPlaceholders = [icon: "@drawable/ic_launcher"]
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = '21'
    }
    buildFeatures {
        compose true
        buildConfig = true
    }
    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }

}

kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation platform('androidx.compose:compose-bom:2025.06.00')
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.activity:activity-compose:1.10.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-compose:2.9.1'
    debugImplementation 'androidx.compose.ui:ui-tooling'
    implementation 'cafe.adriel.voyager:voyager-navigator:1.1.0-beta03'
    implementation 'cafe.adriel.voyager:voyager-transitions:1.1.0-beta03'
    implementation 'androidx.glance:glance-appwidget:1.1.1'

    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.code.gson:gson:2.11.0'

    implementation "androidx.work:work-runtime-ktx:2.10.1"
    implementation "androidx.documentfile:documentfile:1.1.0"
    implementation "androidx.lifecycle:lifecycle-process:2.9.1"


    implementation "androidx.datastore:datastore-preferences:1.1.7"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.1"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.9.1"

    fullImplementation 'com.google.android.gms:play-services-base:18.10.0'
    fullImplementation 'com.google.android.gms:play-services-location:21.3.0'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.14.1'
}